[build]
  # 告诉 Netlify 运行刚才在 package.json 里写的 build 命令
  command = "npm run build"
  # 告诉 Netlify 部署 dist 目录
  publish = "dist"

# 优化图片等静态资源的缓存
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"